include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - avoid_relative_lib_imports
    - cancel_subscriptions
    - use_key_in_widget_constructors
    - always_put_control_body_on_new_line
    - require_trailing_commas
    - prefer_final_in_for_each
    - always_declare_return_types
    - close_sinks
    - comment_references
    - always_use_package_imports
    - avoid_dynamic_calls
    - use_super_parameters