name: Publish dry run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: FVM config
        id: fvm-config-action
        uses: kuhnroyal/flutter-fvm-config-action@v2

      - name: Configure flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - name: Copy credentials
        run: |
          mkdir -p ~/Library/Application\ Support/dart |
          cat <<EOF > ~/Library/Application\ Support/dart/pub-credentials.json ${{ secrets.PUB_CREDENTIALS_JSON }} EOF |
          mkdir -p ~/.pub-cache |
          ln -s ~/Library/Application\ Support/dart/pub-credentials.json credentials.json

      - name: Pub get
        run: flutter pub get

      - name: Dry run
        run: flutter pub publish --dry-run