name: Publish

on:
  release:
    types: [ published ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: FVM config
        id: fvm-config-action
        uses: kuhnroyal/flutter-fvm-config-action@v2



  publish:
    needs: setup
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      environment: pub.dev

  flutter-publish:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.setup.outputs.FLUTTER_VERSION || '' }}
          channel: ${{ needs.setup.outputs.FLUTTER_CHANNEL || 'stable' }}

      - name: Pub get
        run: flutter pub get

      - name: Publish
        run: flutter pub publish -f